image: maven:3-jdk-8

stages:
  - build

build:
  stage: build
  tags:
    - shared-fi
  script:
    - mvn clean install
  rules:
    - if: $CI_MERGE_REQUEST_ID 
    - if: $CI_COMMIT_BRANCH == 'master'
